### ISSUE TITLE
Bad Endpoints

### ISSUE THREAD

**Issue by lavoy** [MetaphoricalSheep/MPOS.API.Wrapper#1]
Hello,

I just tried a few of these out and it looks like `gethourlyhashrates` and `getnavbardata` don't work. Where did you find these endpoints documented?

Thanks!

**Comment by MetaphoricalSheep** [comment]
Hi there,

I used https://github.com/MPOS/php-mpos/wiki/API-Reference to get the
endpoints and then used https://suprnova.cc
to build the wrapper.

I'll take a look over the weekend and check if I can spot the problem. Feel
free to open a pr if you want to fix it before then.

Kind regards,
Pieter Fourie

**Comment by lavoy** [comment]
Looks like that API is currently broken. Thanks!
